---
secretGenerator:
- name: mysql-config
  namespace: wordpress
  literals:
  - dbname=wordpress
  - user=test
  - password=testpass
  - rootpass=randomrootpass

resources:
- namespace.yml
- mysql-deployment.yml
- mysql-pvc.yml
- mysql-pv.yml
- mysql-clusterip.yml
- wordpress-deployment.yml
- wp-pvc.yml
- wp-pv.yml
- wp-nodeport.yml

