---
#assign the pvc for the storage volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: wordpress
  labels:
    app: wordpress
spec:
  storageClassName: manual-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi