---
#make the storage volume for mysql database
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: wordpress
  labels:
    app: wordpress
    tier: backend
spec:
  storageClassName: manual-config
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mysql-wp-data